/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChannelType : Enum ChannelType.

/// Enum ChannelType.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChannelType {
    #[serde(rename = "TV")]
    Tv,
    #[serde(rename = "Radio")]
    Radio,

}

impl ToString for ChannelType {
    fn to_string(&self) -> String {
        match self {
            Self::Tv => String::from("TV"),
            Self::Radio => String::from("Radio"),
        }
    }
}

impl Default for ChannelType {
    fn default() -> ChannelType {
        Self::Tv
    }
}




