/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreatePlaylistDto : Create new playlist dto.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlaylistDto {
    /// Gets or sets the name of the new playlist.
    #[serde(rename = "Name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// Gets or sets item ids to add to the playlist.
    #[serde(rename = "Ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<uuid::Uuid>>,
    /// Gets or sets the user id.
    #[serde(rename = "UserId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<uuid::Uuid>>,
    /// Gets or sets the media type.
    #[serde(rename = "MediaType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub media_type: Option<Option<String>>,
}

impl CreatePlaylistDto {
    /// Create new playlist dto.
    pub fn new() -> CreatePlaylistDto {
        CreatePlaylistDto {
            name: None,
            ids: None,
            user_id: None,
            media_type: None,
        }
    }
}


