/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateUserByName : The create user by name request body.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserByName {
    /// Gets or sets the username.
    #[serde(rename = "Name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// Gets or sets the password.
    #[serde(rename = "Password", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub password: Option<Option<String>>,
}

impl CreateUserByName {
    /// The create user by name request body.
    pub fn new() -> CreateUserByName {
        CreateUserByName {
            name: None,
            password: None,
        }
    }
}


