/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FileSystemEntryInfo : Class FileSystemEntryInfo.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileSystemEntryInfo {
    /// Gets the name.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Gets the path.
    #[serde(rename = "Path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::FileSystemEntryType>,
}

impl FileSystemEntryInfo {
    /// Class FileSystemEntryInfo.
    pub fn new() -> FileSystemEntryInfo {
        FileSystemEntryInfo {
            name: None,
            path: None,
            r#type: None,
        }
    }
}


