/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HardwareEncodingType : Enum HardwareEncodingType.

/// Enum HardwareEncodingType.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HardwareEncodingType {
    #[serde(rename = "AMF")]
    Amf,
    #[serde(rename = "QSV")]
    Qsv,
    #[serde(rename = "NVENC")]
    Nvenc,
    #[serde(rename = "V4L2M2M")]
    V4L2M2M,
    #[serde(rename = "VAAPI")]
    Vaapi,
    #[serde(rename = "VideoToolBox")]
    VideoToolBox,

}

impl ToString for HardwareEncodingType {
    fn to_string(&self) -> String {
        match self {
            Self::Amf => String::from("AMF"),
            Self::Qsv => String::from("QSV"),
            Self::Nvenc => String::from("NVENC"),
            Self::V4L2M2M => String::from("V4L2M2M"),
            Self::Vaapi => String::from("VAAPI"),
            Self::VideoToolBox => String::from("VideoToolBox"),
        }
    }
}

impl Default for HardwareEncodingType {
    fn default() -> HardwareEncodingType {
        Self::Amf
    }
}




