/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageOption {
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::ImageType>,
    /// Gets or sets the limit.
    #[serde(rename = "Limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// Gets or sets the minimum width.
    #[serde(rename = "MinWidth", skip_serializing_if = "Option::is_none")]
    pub min_width: Option<i32>,
}

impl ImageOption {
    pub fn new() -> ImageOption {
        ImageOption {
            r#type: None,
            limit: None,
            min_width: None,
        }
    }
}


