/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ImageFormat : Enum ImageOutputFormat.

/// Enum ImageOutputFormat.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImageFormat {
    #[serde(rename = "Bmp")]
    Bmp,
    #[serde(rename = "Gif")]
    Gif,
    #[serde(rename = "Jpg")]
    Jpg,
    #[serde(rename = "Png")]
    Png,
    #[serde(rename = "Webp")]
    Webp,

}

impl ToString for ImageFormat {
    fn to_string(&self) -> String {
        match self {
            Self::Bmp => String::from("Bmp"),
            Self::Gif => String::from("Gif"),
            Self::Jpg => String::from("Jpg"),
            Self::Png => String::from("Png"),
            Self::Webp => String::from("Webp"),
        }
    }
}

impl Default for ImageFormat {
    fn default() -> ImageFormat {
        Self::Bmp
    }
}




