/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MediaPathDtoPathInfo : Gets or sets the path info.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaPathDtoPathInfo {
    #[serde(rename = "Path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "NetworkPath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub network_path: Option<Option<String>>,
}

impl MediaPathDtoPathInfo {
    /// Gets or sets the path info.
    pub fn new() -> MediaPathDtoPathInfo {
        MediaPathDtoPathInfo {
            path: None,
            network_path: None,
        }
    }
}


