/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MediaPathDto : Media Path dto.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaPathDto {
    /// Gets or sets the name of the library.
    #[serde(rename = "Name")]
    pub name: String,
    /// Gets or sets the path to add.
    #[serde(rename = "Path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
    #[serde(rename = "PathInfo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path_info: Option<Option<Box<crate::models::MediaPathDtoPathInfo>>>,
}

impl MediaPathDto {
    /// Media Path dto.
    pub fn new(name: String) -> MediaPathDto {
        MediaPathDto {
            name,
            path: None,
            path_info: None,
        }
    }
}


