/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MediaStreamType : Enum MediaStreamType.

/// Enum MediaStreamType.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MediaStreamType {
    #[serde(rename = "Audio")]
    Audio,
    #[serde(rename = "Video")]
    Video,
    #[serde(rename = "Subtitle")]
    Subtitle,
    #[serde(rename = "EmbeddedImage")]
    EmbeddedImage,
    #[serde(rename = "Data")]
    Data,

}

impl ToString for MediaStreamType {
    fn to_string(&self) -> String {
        match self {
            Self::Audio => String::from("Audio"),
            Self::Video => String::from("Video"),
            Self::Subtitle => String::from("Subtitle"),
            Self::EmbeddedImage => String::from("EmbeddedImage"),
            Self::Data => String::from("Data"),
        }
    }
}

impl Default for MediaStreamType {
    fn default() -> MediaStreamType {
        Self::Audio
    }
}




