/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetadataEditorInfo {
    #[serde(rename = "ParentalRatingOptions", skip_serializing_if = "Option::is_none")]
    pub parental_rating_options: Option<Vec<crate::models::ParentalRating>>,
    #[serde(rename = "Countries", skip_serializing_if = "Option::is_none")]
    pub countries: Option<Vec<crate::models::CountryInfo>>,
    #[serde(rename = "Cultures", skip_serializing_if = "Option::is_none")]
    pub cultures: Option<Vec<crate::models::CultureDto>>,
    #[serde(rename = "ExternalIdInfos", skip_serializing_if = "Option::is_none")]
    pub external_id_infos: Option<Vec<crate::models::ExternalIdInfo>>,
    #[serde(rename = "ContentType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<Option<String>>,
    #[serde(rename = "ContentTypeOptions", skip_serializing_if = "Option::is_none")]
    pub content_type_options: Option<Vec<crate::models::NameValuePair>>,
}

impl MetadataEditorInfo {
    pub fn new() -> MetadataEditorInfo {
        MetadataEditorInfo {
            parental_rating_options: None,
            countries: None,
            cultures: None,
            external_id_infos: None,
            content_type: None,
            content_type_options: None,
        }
    }
}


