/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationOptions {
    #[serde(rename = "Options", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub options: Option<Option<Vec<crate::models::NotificationOption>>>,
}

impl NotificationOptions {
    pub fn new() -> NotificationOptions {
        NotificationOptions {
            options: None,
        }
    }
}


