/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NotificationsSummaryDto : The notification summary DTO.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationsSummaryDto {
    /// Gets or sets the number of unread notifications.
    #[serde(rename = "UnreadCount", skip_serializing_if = "Option::is_none")]
    pub unread_count: Option<i32>,
    #[serde(rename = "MaxUnreadNotificationLevel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_unread_notification_level: Option<Option<crate::models::NotificationLevel>>,
}

impl NotificationsSummaryDto {
    /// The notification summary DTO.
    pub fn new() -> NotificationsSummaryDto {
        NotificationsSummaryDto {
            unread_count: None,
            max_unread_notification_level: None,
        }
    }
}


