/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PlaybackInfoResponse : Class PlaybackInfoResponse.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaybackInfoResponse {
    /// Gets or sets the media sources.
    #[serde(rename = "MediaSources", skip_serializing_if = "Option::is_none")]
    pub media_sources: Option<Vec<crate::models::MediaSourceInfo>>,
    /// Gets or sets the play session identifier.
    #[serde(rename = "PlaySessionId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub play_session_id: Option<Option<String>>,
    #[serde(rename = "ErrorCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<Option<crate::models::PlaybackErrorCode>>,
}

impl PlaybackInfoResponse {
    /// Class PlaybackInfoResponse.
    pub fn new() -> PlaybackInfoResponse {
        PlaybackInfoResponse {
            media_sources: None,
            play_session_id: None,
            error_code: None,
        }
    }
}


