/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseProfile {
    #[serde(rename = "Container", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub container: Option<Option<String>>,
    #[serde(rename = "AudioCodec", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub audio_codec: Option<Option<String>>,
    #[serde(rename = "VideoCodec", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub video_codec: Option<Option<String>>,
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::DlnaProfileType>,
    #[serde(rename = "OrgPn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub org_pn: Option<Option<String>>,
    #[serde(rename = "MimeType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<Option<String>>,
    #[serde(rename = "Conditions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Option<Vec<crate::models::ProfileCondition>>>,
}

impl ResponseProfile {
    pub fn new() -> ResponseProfile {
        ResponseProfile {
            container: None,
            audio_codec: None,
            video_codec: None,
            r#type: None,
            org_pn: None,
            mime_type: None,
            conditions: None,
        }
    }
}


