/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SetRepeatModeRequestDto : Class SetRepeatModeRequestDto.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetRepeatModeRequestDto {
    #[serde(rename = "Mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<crate::models::GroupRepeatMode>,
}

impl SetRepeatModeRequestDto {
    /// Class SetRepeatModeRequestDto.
    pub fn new() -> SetRepeatModeRequestDto {
        SetRepeatModeRequestDto {
            mode: None,
        }
    }
}


