/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.11
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TranscodeReason {
    #[serde(rename = "ContainerNotSupported")]
    ContainerNotSupported,
    #[serde(rename = "VideoCodecNotSupported")]
    VideoCodecNotSupported,
    #[serde(rename = "AudioCodecNotSupported")]
    AudioCodecNotSupported,
    #[serde(rename = "SubtitleCodecNotSupported")]
    SubtitleCodecNotSupported,
    #[serde(rename = "AudioIsExternal")]
    AudioIsExternal,
    #[serde(rename = "SecondaryAudioNotSupported")]
    SecondaryAudioNotSupported,
    #[serde(rename = "VideoProfileNotSupported")]
    VideoProfileNotSupported,
    #[serde(rename = "VideoLevelNotSupported")]
    VideoLevelNotSupported,
    #[serde(rename = "VideoResolutionNotSupported")]
    VideoResolutionNotSupported,
    #[serde(rename = "VideoBitDepthNotSupported")]
    VideoBitDepthNotSupported,
    #[serde(rename = "VideoFramerateNotSupported")]
    VideoFramerateNotSupported,
    #[serde(rename = "RefFramesNotSupported")]
    RefFramesNotSupported,
    #[serde(rename = "AnamorphicVideoNotSupported")]
    AnamorphicVideoNotSupported,
    #[serde(rename = "InterlacedVideoNotSupported")]
    InterlacedVideoNotSupported,
    #[serde(rename = "AudioChannelsNotSupported")]
    AudioChannelsNotSupported,
    #[serde(rename = "AudioProfileNotSupported")]
    AudioProfileNotSupported,
    #[serde(rename = "AudioSampleRateNotSupported")]
    AudioSampleRateNotSupported,
    #[serde(rename = "AudioBitDepthNotSupported")]
    AudioBitDepthNotSupported,
    #[serde(rename = "ContainerBitrateExceedsLimit")]
    ContainerBitrateExceedsLimit,
    #[serde(rename = "VideoBitrateNotSupported")]
    VideoBitrateNotSupported,
    #[serde(rename = "AudioBitrateNotSupported")]
    AudioBitrateNotSupported,
    #[serde(rename = "UnknownVideoStreamInfo")]
    UnknownVideoStreamInfo,
    #[serde(rename = "UnknownAudioStreamInfo")]
    UnknownAudioStreamInfo,
    #[serde(rename = "DirectPlayError")]
    DirectPlayError,
    #[serde(rename = "VideoRangeTypeNotSupported")]
    VideoRangeTypeNotSupported,

}

impl ToString for TranscodeReason {
    fn to_string(&self) -> String {
        match self {
            Self::ContainerNotSupported => String::from("ContainerNotSupported"),
            Self::VideoCodecNotSupported => String::from("VideoCodecNotSupported"),
            Self::AudioCodecNotSupported => String::from("AudioCodecNotSupported"),
            Self::SubtitleCodecNotSupported => String::from("SubtitleCodecNotSupported"),
            Self::AudioIsExternal => String::from("AudioIsExternal"),
            Self::SecondaryAudioNotSupported => String::from("SecondaryAudioNotSupported"),
            Self::VideoProfileNotSupported => String::from("VideoProfileNotSupported"),
            Self::VideoLevelNotSupported => String::from("VideoLevelNotSupported"),
            Self::VideoResolutionNotSupported => String::from("VideoResolutionNotSupported"),
            Self::VideoBitDepthNotSupported => String::from("VideoBitDepthNotSupported"),
            Self::VideoFramerateNotSupported => String::from("VideoFramerateNotSupported"),
            Self::RefFramesNotSupported => String::from("RefFramesNotSupported"),
            Self::AnamorphicVideoNotSupported => String::from("AnamorphicVideoNotSupported"),
            Self::InterlacedVideoNotSupported => String::from("InterlacedVideoNotSupported"),
            Self::AudioChannelsNotSupported => String::from("AudioChannelsNotSupported"),
            Self::AudioProfileNotSupported => String::from("AudioProfileNotSupported"),
            Self::AudioSampleRateNotSupported => String::from("AudioSampleRateNotSupported"),
            Self::AudioBitDepthNotSupported => String::from("AudioBitDepthNotSupported"),
            Self::ContainerBitrateExceedsLimit => String::from("ContainerBitrateExceedsLimit"),
            Self::VideoBitrateNotSupported => String::from("VideoBitrateNotSupported"),
            Self::AudioBitrateNotSupported => String::from("AudioBitrateNotSupported"),
            Self::UnknownVideoStreamInfo => String::from("UnknownVideoStreamInfo"),
            Self::UnknownAudioStreamInfo => String::from("UnknownAudioStreamInfo"),
            Self::DirectPlayError => String::from("DirectPlayError"),
            Self::VideoRangeTypeNotSupported => String::from("VideoRangeTypeNotSupported"),
        }
    }
}

impl Default for TranscodeReason {
    fn default() -> TranscodeReason {
        Self::ContainerNotSupported
    }
}




